<?php

namespace ContainerIsvuk5M;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_6pXJlrMService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.6pXJlrM' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.6pXJlrM'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\Admin\\CategoriesController::index' => ['privates', '.service_locator..Ri2R5w', 'get_ServiceLocator__Ri2R5wService', true],
            'App\\Controller\\Admin\\CategoriesController::updateCatgeory' => ['privates', '.service_locator.E7MvU05', 'get_ServiceLocator_E7MvU05Service', true],
            'App\\Controller\\Admin\\PostsController::activatePost' => ['privates', '.service_locator.RL15XL3', 'get_ServiceLocator_RL15XL3Service', true],
            'App\\Controller\\Admin\\PostsController::deletePost' => ['privates', '.service_locator.RL15XL3', 'get_ServiceLocator_RL15XL3Service', true],
            'App\\Controller\\Admin\\PostsController::index' => ['privates', '.service_locator.802BlKB', 'get_ServiceLocator_802BlKBService', true],
            'App\\Controller\\Admin\\PostsController::updatePost' => ['privates', '.service_locator.RL15XL3', 'get_ServiceLocator_RL15XL3Service', true],
            'App\\Controller\\Admin\\SliderController::activateSlider' => ['privates', '.service_locator.lJHNmQl', 'get_ServiceLocator_LJHNmQlService', true],
            'App\\Controller\\Admin\\SliderController::deletePost' => ['privates', '.service_locator.lJHNmQl', 'get_ServiceLocator_LJHNmQlService', true],
            'App\\Controller\\Admin\\SliderController::index' => ['privates', '.service_locator.yuONzAN', 'get_ServiceLocator_YuONzANService', true],
            'App\\Controller\\Admin\\SliderController::updateSlider' => ['privates', '.service_locator.lJHNmQl', 'get_ServiceLocator_LJHNmQlService', true],
            'App\\Controller\\CategoriesController::index' => ['privates', '.service_locator..Ri2R5w', 'get_ServiceLocator__Ri2R5wService', true],
            'App\\Controller\\CategoriesController::single' => ['privates', '.service_locator.mfzFGhu', 'get_ServiceLocator_MfzFGhuService', true],
            'App\\Controller\\ContactController::index' => ['privates', '.service_locator.CpaXrFh', 'get_ServiceLocator_CpaXrFhService', true],
            'App\\Controller\\MainController::index' => ['privates', '.service_locator.yuONzAN', 'get_ServiceLocator_YuONzANService', true],
            'App\\Controller\\PostsController::index' => ['privates', '.service_locator.802BlKB', 'get_ServiceLocator_802BlKBService', true],
            'App\\Controller\\PostsController::single' => ['privates', '.service_locator.EMI3ST_', 'get_ServiceLocator_EMI3STService', true],
            'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.wOdllM6', 'get_ServiceLocator_WOdllM6Service', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.UDgw6Ol', 'get_ServiceLocator_UDgw6OlService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'FM\\ElfinderBundle\\Controller\\ElFinderController::load' => ['privates', '.service_locator.5usv1bv', 'get_ServiceLocator_5usv1bvService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'App\\Controller\\Admin\\CategoriesController:index' => ['privates', '.service_locator..Ri2R5w', 'get_ServiceLocator__Ri2R5wService', true],
            'App\\Controller\\Admin\\CategoriesController:updateCatgeory' => ['privates', '.service_locator.E7MvU05', 'get_ServiceLocator_E7MvU05Service', true],
            'App\\Controller\\Admin\\PostsController:activatePost' => ['privates', '.service_locator.RL15XL3', 'get_ServiceLocator_RL15XL3Service', true],
            'App\\Controller\\Admin\\PostsController:deletePost' => ['privates', '.service_locator.RL15XL3', 'get_ServiceLocator_RL15XL3Service', true],
            'App\\Controller\\Admin\\PostsController:index' => ['privates', '.service_locator.802BlKB', 'get_ServiceLocator_802BlKBService', true],
            'App\\Controller\\Admin\\PostsController:updatePost' => ['privates', '.service_locator.RL15XL3', 'get_ServiceLocator_RL15XL3Service', true],
            'App\\Controller\\Admin\\SliderController:activateSlider' => ['privates', '.service_locator.lJHNmQl', 'get_ServiceLocator_LJHNmQlService', true],
            'App\\Controller\\Admin\\SliderController:deletePost' => ['privates', '.service_locator.lJHNmQl', 'get_ServiceLocator_LJHNmQlService', true],
            'App\\Controller\\Admin\\SliderController:index' => ['privates', '.service_locator.yuONzAN', 'get_ServiceLocator_YuONzANService', true],
            'App\\Controller\\Admin\\SliderController:updateSlider' => ['privates', '.service_locator.lJHNmQl', 'get_ServiceLocator_LJHNmQlService', true],
            'App\\Controller\\CategoriesController:index' => ['privates', '.service_locator..Ri2R5w', 'get_ServiceLocator__Ri2R5wService', true],
            'App\\Controller\\CategoriesController:single' => ['privates', '.service_locator.mfzFGhu', 'get_ServiceLocator_MfzFGhuService', true],
            'App\\Controller\\ContactController:index' => ['privates', '.service_locator.CpaXrFh', 'get_ServiceLocator_CpaXrFhService', true],
            'App\\Controller\\MainController:index' => ['privates', '.service_locator.yuONzAN', 'get_ServiceLocator_YuONzANService', true],
            'App\\Controller\\PostsController:index' => ['privates', '.service_locator.802BlKB', 'get_ServiceLocator_802BlKBService', true],
            'App\\Controller\\PostsController:single' => ['privates', '.service_locator.EMI3ST_', 'get_ServiceLocator_EMI3STService', true],
            'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.wOdllM6', 'get_ServiceLocator_WOdllM6Service', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.UDgw6Ol', 'get_ServiceLocator_UDgw6OlService', true],
            'FM\\ElfinderBundle\\Controller\\ElFinderController:load' => ['privates', '.service_locator.5usv1bv', 'get_ServiceLocator_5usv1bvService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
        ], [
            'App\\Controller\\Admin\\CategoriesController::index' => '?',
            'App\\Controller\\Admin\\CategoriesController::updateCatgeory' => '?',
            'App\\Controller\\Admin\\PostsController::activatePost' => '?',
            'App\\Controller\\Admin\\PostsController::deletePost' => '?',
            'App\\Controller\\Admin\\PostsController::index' => '?',
            'App\\Controller\\Admin\\PostsController::updatePost' => '?',
            'App\\Controller\\Admin\\SliderController::activateSlider' => '?',
            'App\\Controller\\Admin\\SliderController::deletePost' => '?',
            'App\\Controller\\Admin\\SliderController::index' => '?',
            'App\\Controller\\Admin\\SliderController::updateSlider' => '?',
            'App\\Controller\\CategoriesController::index' => '?',
            'App\\Controller\\CategoriesController::single' => '?',
            'App\\Controller\\ContactController::index' => '?',
            'App\\Controller\\MainController::index' => '?',
            'App\\Controller\\PostsController::index' => '?',
            'App\\Controller\\PostsController::single' => '?',
            'App\\Controller\\RegistrationController::register' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'FM\\ElfinderBundle\\Controller\\ElFinderController::load' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\Admin\\CategoriesController:index' => '?',
            'App\\Controller\\Admin\\CategoriesController:updateCatgeory' => '?',
            'App\\Controller\\Admin\\PostsController:activatePost' => '?',
            'App\\Controller\\Admin\\PostsController:deletePost' => '?',
            'App\\Controller\\Admin\\PostsController:index' => '?',
            'App\\Controller\\Admin\\PostsController:updatePost' => '?',
            'App\\Controller\\Admin\\SliderController:activateSlider' => '?',
            'App\\Controller\\Admin\\SliderController:deletePost' => '?',
            'App\\Controller\\Admin\\SliderController:index' => '?',
            'App\\Controller\\Admin\\SliderController:updateSlider' => '?',
            'App\\Controller\\CategoriesController:index' => '?',
            'App\\Controller\\CategoriesController:single' => '?',
            'App\\Controller\\ContactController:index' => '?',
            'App\\Controller\\MainController:index' => '?',
            'App\\Controller\\PostsController:index' => '?',
            'App\\Controller\\PostsController:single' => '?',
            'App\\Controller\\RegistrationController:register' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'FM\\ElfinderBundle\\Controller\\ElFinderController:load' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
