<?php

namespace ContainerIsvuk5M;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_MfzFGhuService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.mfzFGhu' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.mfzFGhu'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'category' => ['privates', '.errored..service_locator.mfzFGhu.App\\Entity\\Categories', NULL, 'Cannot autowire service ".service_locator.mfzFGhu": it references class "App\\Entity\\Categories" but no such service exists.'],
            'categoryRepository' => ['privates', 'App\\Repository\\CategoriesRepository', 'getCategoriesRepositoryService', true],
        ], [
            'category' => 'App\\Entity\\Categories',
            'categoryRepository' => 'App\\Repository\\CategoriesRepository',
        ]);
    }
}
