<?php

namespace Container1SrYcje;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_EMI3STService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.EMI3ST_' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.EMI3ST_'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'post' => ['privates', '.errored..service_locator.EMI3ST_.App\\Entity\\Posts', NULL, 'Cannot autowire service ".service_locator.EMI3ST_": it references class "App\\Entity\\Posts" but no such service exists.'],
            'postsRepository' => ['privates', 'App\\Repository\\PostsRepository', 'getPostsRepositoryService', true],
        ], [
            'post' => 'App\\Entity\\Posts',
            'postsRepository' => 'App\\Repository\\PostsRepository',
        ]);
    }
}
