<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXnoStcZ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXnoStcZ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXnoStcZ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXnoStcZ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXnoStcZ\App_KernelDevDebugContainer([
    'container.build_hash' => 'XnoStcZ',
    'container.build_id' => 'a2cf9b8e',
    'container.build_time' => 1641624183,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXnoStcZ');
